### ISSUE TITLE
 CRITICAL: The following methods must each be used in at least one test.

### ISSUE THREAD

**Issue by egordya** [johanneslindq/TDA553-lab1#3]
- [x] gas
- [x] brake
- [x] move
- [x] turnLeft
- [x] turnRight

You need to create JUnit tests to pass the lab. Please read lab description. 
Make sure to test specification (behaviour), not implemementation.

**Comment by squaasher** [comment]
![image](https://user-images.githubusercontent.com/40966920/205283077-a2ba8088-66e9-432c-848c-8f9a05db0e93.png)

**Comment by egordya** [comment]
You should still write JUnit tests, just not for 100% coverage. You can still test 60% or 50% coverage, as long as you test those methods. Please ask/write to a TA or Robin if you are still unsure.

**Comment by johanneslindq** [comment]
Could you take another look, we've added tests.
